//
// GifList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct GifList: Codable {

    public var meta: Meta?
    public var pagination: Pagination?
    public var data: [Gif]?

    public init(meta: Meta?, pagination: Pagination?, data: [Gif]?) {
        self.meta = meta
        self.pagination = pagination
        self.data = data
    }


}

