//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Image: Codable {

    public var url: String?
    public var width: String?
    public var heigh: String?
    public var size: String?
    public var mp4: String?
    public var mp4Size: String?
    public var webp: String?
    public var webpSize: String?

    public init(url: String?, width: String?, heigh: String?, size: String?, mp4: String?, mp4Size: String?, webp: String?, webpSize: String?) {
        self.url = url
        self.width = width
        self.heigh = heigh
        self.size = size
        self.mp4 = mp4
        self.mp4Size = mp4Size
        self.webp = webp
        self.webpSize = webpSize
    }

    public enum CodingKeys: String, CodingKey { 
        case url
        case width
        case heigh
        case size
        case mp4
        case mp4Size = "mp4_size"
        case webp
        case webpSize = "webp_size"
    }


}

